add shell

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,35 +1,53 @@
 name: verl github runner demo
 description: 'Build github runner with vemlp'
 inputs:
+  mode:
+    description: >-
+      create or destory
+    required: true
   faas-url: 
-    description: 'Fass url'
-    required: true
-  image: 
-    description: 'vemlp image'
-    required: true
+    description: >-
+      Fass url
+      This input is required if you use the 'create' mode.
+    required: false
+  mlp-image: 
+    description: >-
+      Vemlp image
+      This input is required if you use the 'create' mode.
+    required: false
+  mlp-task-id:
+    description: >-
+      MLP task id
+      This input is required if you use the 'destory' mode.
+    required: false
 outputs:
     runner-label: 
       description: 'runner label'
-      value: ${{ steps.create-runner.outputs.runner_label }}
+      value: ${{ steps.process-runnr.outputs.runner_label }}
     mlp-task-id:
       description: 'mlp task id'
-      value: ${{ steps.create-runner.outputs.mlp_task_id }}
+      value: ${{ steps.process-runnr.outputs.mlp_task_id }}
 runs:
   using: "composite"
   steps:
-    - name: create runner
-      id: create-runner
+    - name: process runner
+      id: process-runnr
       run: |
-        resp=$(curl -X POST "${{ inputs.faas-url }}" \
-        -d '{"Image": "${{ inputs.image }}"}')
-        echo $resp
-        runner_label=$(echo $resp | jq -r '.runner_label')
-        echo $runner_label
-        if [[ -z $runner_label || $runner_label == "null" ]]; then
-          echo "create runner failed"
-          exit 1
+        if [[ "${{ inputs.mode }}" == "create" ]]; then
+          resp=$(curl -X POST "${{ inputs.faas-url }}/create" \
+          -d '{"Image": "${{ inputs.mlp-image }}"}')
+          echo $resp
+          runner_label=$(echo $resp | jq -r '.runner_label')
+          echo $runner_label
+          if [[ -z $runner_label || $runner_label == "null" ]]; then
+            echo "create runner failed"
+            exit 1
+          fi
+          echo "runner_label=$runner_label" >> $GITHUB_OUTPUT   
+          mlp_task_id=$(echo $resp | jq -r '.task_id')
+          echo "mlp_task_id=$mlp_task_id" >> $GITHUB_OUTPUT
+        else
+          resp=$(curl -X POST "${{ env.DYNAMIC_RUNNER_ENDPOINT }}/delete" \
+          -d '{"TaskId": "${{ inputs.mlp-task-id }}"}')
         fi
-        echo "runner_label=$runner_label" >> $GITHUB_OUTPUT   
-        mlp_task_id=$(echo $resp | jq -r '.task_id')
-        echo "mlp_task_id=$mlp_task_id" >> $GITHUB_OUTPUT 
       shell: bash
